# Machine Learning Zoomcamp

### Introduction to Numpy

Plan:
* Crearing Arrays
* Multi-dimentional Arrays
* Randomly generated Arrays
* Element-wise:
    * Comparison operations
    * Logical operations
* Summarizing operations

In [1]:
# Importing the library
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating arrays

In [3]:
#Creating arrays
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,4,5,6,7,13])
a

array([ 1,  2,  3,  4,  5,  6,  7, 13])

In [7]:
a[2]

np.int64(3)

In [8]:
a[1] = 16
a

array([ 1, 16,  3,  4,  5,  6,  7, 13])

In [9]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Mult- dimentional array

In [11]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
p = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
p[0,2] = 16
p

array([[ 1,  2, 16],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [14]:
p[1]
p[1] = [28,1,11]
p

array([[ 1,  2, 16],
       [28,  1, 11],
       [ 7,  8,  9]])

## Randomly Generated Arrays

In [15]:
np.random.seed(2)
np.random.rand(5,3).round(2)

array([[0.44, 0.03, 0.55],
       [0.44, 0.42, 0.33],
       [0.2 , 0.62, 0.3 ],
       [0.27, 0.62, 0.53],
       [0.13, 0.51, 0.18]])

In [16]:
np.random.randn(4,5)

array([[ 0.48008484,  0.38699051,  1.21046817, -0.02012954,  0.01039395],
       [-0.83283795, -0.11601058, -0.70162767, -1.38939342,  0.49059556],
       [-0.21943638, -0.30837444, -0.45571477, -2.12452767,  0.54979824],
       [-1.16790025,  1.08006357, -3.4918143 ,  1.27004848, -0.48921489]])

In [51]:
np.random.seed(2)
k = 100*np.random.rand(3,4).round(3)
k

array([[43.6,  2.6, 55. , 43.5],
       [42. , 33. , 20.5, 61.9],
       [30. , 26.7, 62.1, 52.9]])

In [18]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(3,4))

array([[40, 15, 72, 22],
       [43, 82, 75,  7],
       [34, 49, 95, 75]])

## Element-wise operations

In [19]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [23]:
a + 3

array([3, 4, 5, 6, 7])

In [37]:
b = (10 + (a * 2)) * 2/100
b

array([0.2 , 0.24, 0.28, 0.32, 0.36])

In [24]:
a + b

array([0.2 , 1.24, 2.28, 3.32, 4.36])

## Comparison operations

In [25]:
a

array([0, 1, 2, 3, 4])

In [26]:
a >= 2

array([False, False,  True,  True,  True])

In [38]:
b *=4
b

array([0.8 , 0.96, 1.12, 1.28, 1.44])

In [39]:
a > b

array([False,  True,  True,  True,  True])

In [44]:
a[a > b]

array([1, 2, 3, 4])

## Summarizing operations

In [45]:
a

array([0, 1, 2, 3, 4])

In [46]:
a.min()

np.int64(0)

In [47]:
a.max()

np.int64(4)

In [49]:
a.sum()

np.int64(10)

In [50]:
a.mean()

np.float64(2.0)

In [54]:
k


array([[43.6,  2.6, 55. , 43.5],
       [42. , 33. , 20.5, 61.9],
       [30. , 26.7, 62.1, 52.9]])

In [58]:
print(k.mean())

39.48333333333334


In [59]:
print(k.sum())

473.80000000000007


In [61]:
print(k.std())

17.054658861697845
