# Linear Algebra

In [1]:
# Importing the library
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating arrays

In [3]:
#Creating the U and V vectors
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])

In [4]:
#Inspecting the vectors U and V

In [5]:
print(f'The shape of U:')
print(u.shape)
print(u)
print(f'The shape of V:')
print(v.shape)
print(v)

The shape of U:
(4,)
[2 4 5 6]
The shape of V:
(4,)
[1 0 0 2]


## Using the inplut Dot method

In [6]:
#get the dot 
u.dot(v)

np.int64(14)

## Using a custom define method

### Vector to Vector Multplication

In [7]:
def vector_vector_multplication(v,u):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result = u[i] * v[i]
    return result

vector_vector_multplication(u,v)

np.int64(12)

### Matrix -  Vector Multplication

In [8]:
# 3 x 4 matrix
m = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
m

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [9]:
# 4 x 1 column vector
k = np.array([
    [1],
    [0.5],
    [2],
    [1]
])
k

array([[1. ],
       [0.5],
       [2. ],
       [1. ]])

In [14]:

def matrix_vector_multplication(m, k):
    m = np.array(m)
    k = np.array(k)

    assert m.shape[1] == k.shape[0]
    n = m.shape[0]
    result = np.zeros(n)

    for i in range(n):
        result[i] = vector_vector_multplication(m[i], k)

    return result



print(matrix_vector_multplication(m, k))


[20.   6.   8.5]


/tmp/ipykernel_28284/4146873605.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  result += float(u[i] * v[i])


In [11]:
m.dot(k)

array([[20. ],
       [ 6. ],
       [ 8.5]])