# Linear Algebra

In [1]:
# Importing the library
import numpy as np
import warnings
warnings.filterwarnings("ignore")


In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating arrays

In [3]:
#Creating the U and V vectors
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])

In [4]:
#Inspecting the vectors U and V

In [5]:
print(f'The shape of U:')
print(u.shape)
print(u)
print(f'The shape of V:')
print(v.shape)
print(v)

The shape of U:
(4,)
[2 4 5 6]
The shape of V:
(4,)
[1 0 0 2]


## Using the inplut Dot method

In [6]:
#get the dot 
u.dot(v)

np.int64(14)

## Using a custom define method

### Vector to Vector Multplication

In [7]:
def vector_vector_multplication(v,u):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result = u[i] * v[i]
    return result

print(vector_vector_multplication(u,v))

12


### Matrix -  Vector Multplication

In [8]:
# 3 x 4 matrix
m = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
m.shape

(3, 4)

In [9]:
# 4 x 1 column vector
k = np.array([
    [1],
    [0.5],
    [2],
    [1]
])

print(k.shape)

(4, 1)


In [10]:

def matrix_vector_multplication(m, k):
    u = np.array(m)
    v = np.array(k)

    assert u.shape[1] == v.shape[0]
    n_rows = u.shape[0]
    
    result = np.zeros(n_rows)

    for i in range(n_rows):
            result[i] = np.dot(u[i],v)

    return result



print(matrix_vector_multplication(m, k))


[20.   6.   8.5]


## Matrix by Matrix Multplication

In [17]:
def matrix_matrix_multi(u,v):
    assert v.shape[1] == u.shape[0]

    n_rows = u.shape[0]
    n_cols = v.shape[1]

    result = np.zeros((n_rows,n_cols))

    for i in range(n_rows):
        for j in range(n_cols):
            result[i][j]= np.dot(u[i],v[:,j])

    return result

In [24]:
u = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(u.shape)

v = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])
print(v.shape)

(2, 3)
(3, 2)


In [25]:
matrix_matrix_multi(u,v)

array([[ 58.,  64.],
       [139., 154.]])

In [19]:
u.dot(v)

array([[ 58,  64],
       [139, 154]])

## Identity Matrix

In [26]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
# Identity matrix multplied by matrix == that vary matrix
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [2, 4, 1]])
M.shape

I.dot(M)

array([[1., 2., 3.],
       [4., 5., 6.],
       [2., 4., 1.]])

## Inverse

In [32]:
m_inv = np.linalg.inv(M)
m_inv

array([[-1.26666667,  0.66666667, -0.2       ],
       [ 0.53333333, -0.33333333,  0.4       ],
       [ 0.4       ,  0.        , -0.2       ]])

In [38]:
#The product of Inverse and the matrix set is Identity Matrix

m_inv.dot(M).round()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])